import { InferGetStaticPropsType } from "next"
import Head from "next/head"
import { getStaticProps, PageInfo } from "../../pages"
import { Layout } from "../Layout"
import { WelcomeBanner } from "./WelcomeBanner"
import { MostRecentPagesSection } from "./MostRecentPages"

type Props = {
  mostRecentPages: Array<PageInfo>
}

const Home : InferGetStaticPropsType<typeof getStaticProps> = ({ mostRecentPages } : Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <WelcomeBanner />
        {mostRecentPages && mostRecentPages.length > 0 &&
          <MostRecentPagesSection pages={mostRecentPages} />
        }
      </Layout>
    </div>
  )
}

export default Home
