import { InferGetStaticPropsType } from "next"
import Head from "next/head"
import { getStaticProps, PageInfo } from "../../pages"
import { Layout } from "../Layout"
import { RecentPageEntry } from "../RecentPageEntry"
import { WelcomeBanner } from "../WelcomeBanner"

type Props = {
  mostRecentPages: Array<PageInfo>
}



const Home : InferGetStaticPropsType<typeof getStaticProps> = ({ mostRecentPages } : Props) => {
  return (
    <div className='bg-blue-50 h-full min-h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <WelcomeBanner />
        {mostRecentPages.map((page, index) => (
          <RecentPageEntry
            key={page.title + index}
            page={page}
          />
        ))}
      </Layout>
    </div>
  )
}

export default Home
